%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# camera topics
left_img_topic:  /csi/image_0
right_img_topic:  /csi/image_1

# Stereo calibration file name
calib_file_name: calibration/cam_stereo_mount_3.yml

# Calibration image width and height
calib_width: 640 #752
calib_height: 480 #480

# Rectified image width and height
out_width: 640

out_height: 480

# Set d=1 for cam to robot frame calibration
debug: 0

# display image?
displayImage: 1

# disparity maximum and minimum
disparityMax: 255
disparityMin: 2

# maximum point distance (z)
distanceMax: 5
distanceMin: 0.00

# max/min x and y
max_x: 650
min_x: 102 
max_y: 480
min_y: 50

# disparity map generation method
method: 1 # 0 for StereoBM, 1 for StereoSGBM

# conduct stereoRectify?
conductStereoRectify: 1

# use WLS filter？
UseWLSfilter: 1
Lambda: 0.5 #0.4 #0
SigmaColor: 1000 #10

# common params for both methods:
MinDisparity: 7
NumDisparities: 32 #32
PreFilterCap: 63
UniquenessRatio: 115 #50 #115
SpeckleWindowSize: 10 #0

# for StereoBM (Block Matching) matcher params
RangeOfDisparity: 16 # dividable by 16
SizeOfBlockWindow: 7 # must be odd 7
PreFilterSize: 255
SmallerBlockSize: 7
TextureThreshold: 155

# for StereoSGBM (Semi-Global Block Matching) matcher params
P1: 0 #700
P2: 0 #2800
disp12MaxDiff: 50 #10
speckleRange: 3 #3
fullDP: 0 #0

# useful param
UseRadiusOutlierRemoval: 1
Radius: 0.1 # meter
MinNeighbor: 100

# use PCL filtering? be carefull with this option!
UsePCLfiltering: 0
UseStatisticalOutlierRemoval: 0
mean_k: 50
stdThres: 1

# not implemented yet
UseConditionalRemoval: 0
Min: 0.0
Max: 3.0

