%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# camera topics
left_img_topic:  /csi/image_0
right_img_topic:  /csi/image_1

# Stereo calibration file name
calib_file_name: calibration/cam_stereo_exrigid.yml

# Calibration image width and height
calib_width: 1280 #752
calib_height: 720 #480

# Rectified image width and height
out_width: 1280
out_height: 720

# Set d=1 for cam to robot frame calibration
debug: 0

# display image?
displayImage: 1

# disparity maximum and minimum
disparityMax: 30
disparityMin: 2

# maximum point distance (z)
distanceMax: 10
distanceMin: 0.1

# max/min x and y
max_x: 650
min_x: 102 
max_y: 480
min_y: 50

# disparity map generation method
method: 0 # 0 for StereoBM, 1 for StereoSGBM

# conduct stereoRectify?
conductStereoRectify: 0

# use WLS filter？
UseWLSfilter: 1
Lambda: 0 #0.4 #0
SigmaColor: 10 #10

# common params for both methods:
MinDisparity: 7
NumDisparities: 32 #32
PreFilterCap: 63
UniquenessRatio: 50 #115
SpeckleWindowSize: 0 #0

# for StereoBM (Block Matching) matcher params
RangeOfDisparity: 16 # dividable by 16
SizeOfBlockWindow: 7 # must be odd 7
PreFilterSize: 255
SmallerBlockSize: 7
TextureThreshold: 155

# for StereoSGBM (Semi-Global Block Matching) matcher params
P1: 700
P2: 2800
disp12MaxDiff: 20 #10
speckleRange: 10 #3
fullDP: 1 #0

# useful param
UseRadiusOutlierRemoval: 1
Radius: 0.1 # meter
MinNeighbor: 100

# use PCL filtering? be carefull with this option!
UsePCLfiltering: 0
UseStatisticalOutlierRemoval: 0
mean_k: 50
stdThres: 1

# not implemented yet
UseConditionalRemoval: 0
Min: 0.0
Max: 3.0

